name: Build APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取项目全部代码
        uses: actions/checkout@v4

      - name: 安装JDK 11（安卓编译官方适配版本）
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 自动修复&补全所有缺失的Gradle全套文件
        run: gradle wrapper --gradle-version 7.2

      - name: 给脚本开启可执行权限
        run: chmod +x gradlew

      - name: 开始编译Debug安装包
        run: ./gradlew assembleDebug --no-daemon

      - name: 打包成品APK供下载
        uses: actions/upload-artifact@v4
        with:
          name: 奶昔小希_控制APP
          path: app/build/outputs/apk/debug/*.apk
