name: Build APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取全部项目代码
        uses: actions/checkout@v4

      - name: 配置JDK17环境
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 给gradlew添加执行权限
        run: chmod +x gradlew

      - name: 编译安卓APK安装包
        run: ./gradlew assembleDebug

      - name: 打包上传成品APK
        uses: actions/upload-artifact@v4
        with:
          name: 奶昔小希_控制APP
          path: app/build/outputs/apk/debug/*.apk
